INSERT INTO Items (id, name) VALUES
(1, 'Laptop Gamer Dell Alienware m16 R1'),
(2, 'Teclado Mecánico Razer BlackWidow V4 Pro'),
(3, 'Mouse Inalámbrico Logitech MX Master 3S'),
(4, 'Monitor Curvo Samsung Odyssey G9 49"'),
(5, 'Tarjeta Gráfica NVIDIA GeForce RTX 4080 Super'),
(6, 'Procesador Intel Core i9-14900K'),
(7, 'Memoria RAM Corsair Vengeance RGB DDR5 32GB'),
(8, 'Disco Duro SSD Samsung 990 Pro 2TB'),
(9, 'Placa Base ASUS ROG Strix Z790-E Gaming WiFi'),
(10, 'Fuente de Alimentación Seasonic Prime TX-1000 1000W'),
(11, 'Refrigeración Líquida Corsair iCUE H150i Elite Capellix'),
(12, 'Gabinete ATX Lian Li O11 Dynamic EVO'),
(13, 'Auriculares Gaming HyperX Cloud Alpha Wireless'),
(14, 'Micrófono Blue Yeti X USB'),
(15, 'Cámara Web Logitech C920S Pro HD'),
(16, 'Silla Ergonómica Secretlab Titan EVO 2022'),
(17, 'Impresora Multifunción HP Envy 6020e'),
(18, 'Altavoces Logitech Z407 Bluetooth'),
(19, 'Router WiFi 6 TP-Link Archer AX73'),
(20, 'Smart TV LG OLED evo C3 65"'),
(21, 'Consola de Videojuegos PlayStation 5 Slim'),
(22, 'Control Inalámbrico Xbox Elite Series 2 Core'),
(23, 'Juego Elden Ring Edición de Coleccionista'),
(24, 'Teléfono Inteligente Apple iPhone 15 Pro Max'),
(25, 'Reloj Inteligente Samsung Galaxy Watch 6 Classic'),
(26, 'Tableta Gráfica Wacom Intuos Pro Medium'),
(27, 'Libro "Cien años de soledad" de Gabriel García Márquez'),
(28, 'Cafetera Superautomática DeLonghi Magnifica Evo'),
(29, 'Aspiradora Robot iRobot Roomba j9+'),
(30, 'Horno de Microondas Panasonic NN-SN96JS'),
(31, 'Batidora de Mano KitchenAid Artisan Mini Plus'),
(32, 'Nevera Inteligente Samsung Family Hub'),
(33, 'Lavadora Carga Frontal LG WM4000HWA'),
(34, 'Secadora Eléctrica Whirlpool WED5000DW'),
(35, 'Bicicleta de Montaña Trek Marlin 7'),
(36, 'Zapatos Deportivos Nike Air Zoom Pegasus 40'),
(37, 'Chaqueta Impermeable The North Face Resolve 2'),
(38, 'Mochila Osprey Farpoint 40 Travel Pack'),
(39, 'Tienda de Campaña Coleman Sundome 4 Personas'),
(40, 'Linterna Frontal Petzl Actik Core'),
(41, 'Set de Ollas y Sartenes T-fal Ultimate Hard Anodized'),
(42, 'Juego de Cuchillos de Cocina Victorinox Swiss Classic'),
(43, 'Tabla de Cortar Bambú Orgánico Totally Bamboo'),
(44, 'Toallas de Baño Turcas de Algodón Amsonia'),
(45, 'Set de Sábanas de Lino Belgian Flax West Elm'),
(46, 'Almohada de Espuma Viscoelástica Tempur-Pedic Cloud'),
(47, 'Manta Pesada Gravity Blanket Original'),
(48, 'Difusor de Aceites Esenciales Vitruvi Stone'),
(49, 'Vela Aromática Diptyque Baies'),
(50, 'Planta de Interior Monstera Deliciosa');
